# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pj4Ivf02vPxZUpBnUjf_Oc-YIoYgKEIN
"""

# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6q8GJwJ73_KUJUmmQvQJufNNJFpRr9C
"""

import cv2
import numpy as np
import tkinter as tk
from PIL import Image, ImageTk
import math
import sys
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# ------------------ Models ------------------

faceNet = cv2.dnn.readNet(
    "face_detector/deploy.prototxt",
    "face_detector/res10_300x300_ssd_iter_140000.caffemodel"
)

maskNet = load_model("mask_detector.model")

# ------------------ Distance Function ------------------

def count_distance_violations(locs, threshold_px=400):
    centers = []
    for (startX, startY, endX, endY) in locs:
        cx = int((startX + endX) / 2)
        cy = int((startY + endY) / 2)
        centers.append((cx, cy))

    violators = set()
    for i in range(len(centers)):
        for j in range(i + 1, len(centers)):
            dx = centers[i][0] - centers[j][0]
            dy = centers[i][1] - centers[j][1]
            dist = math.sqrt(dx*dx + dy*dy)
            if dist < threshold_px:
                violators.add(i)
                violators.add(j)

    return len(violators)

# ------------------ Detection ------------------

def detect(frame):
    (h, w) = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(
        frame, 1.0, (300, 300),
        (104.0, 177.0, 123.0)
    )

    faceNet.setInput(blob)
    detections = faceNet.forward()

    faces = []
    locs = []

    for i in range(0, detections.shape[2]):
        confidence = detections[0, 0, i, 2]
        if confidence > 0.5:
            box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
            (startX, startY, endX, endY) = box.astype("int")

            startX = max(0, startX)
            startY = max(0, startY)
            endX = min(w - 1, endX)
            endY = min(h - 1, endY)

            face = frame[startY:endY, startX:endX]
            if face.size == 0:
                continue

            face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)
            face = cv2.resize(face, (224, 224))
            face = preprocess_input(face)

            faces.append(face)
            locs.append((startX, startY, endX, endY))

    preds = []
    if len(faces) > 0:
        faces = np.array(faces, dtype="float32")
        preds = maskNet.predict(faces, verbose=0)

    return locs, preds

# ------------------ UI Panel ------------------

class FogPanel:
    def __init__(self, parent, video_path, fog_name, cell_w=420, cell_h=240):
        self.video_path = video_path
        self.fog_name = fog_name
        self.cell_w = cell_w
        self.cell_h = cell_h

        self.cap = cv2.VideoCapture(video_path)
        self.running = True

        self.frame = tk.Frame(parent, bd=2, relief="groove", padx=6, pady=6)

        self.title = tk.Label(self.frame, text=fog_name, font=("Arial", 14, "bold"))
        self.title.pack(anchor="w")

        self.video_label = tk.Label(self.frame)
        self.video_label.pack()

        self.stats_frame = tk.Frame(self.frame)
        self.stats_frame.pack(pady=4)

        self.people_label = tk.Label(self.stats_frame, text="People: 0", font=("Arial", 11))
        self.people_label.grid(row=0, column=0, padx=8)

        self.mask_label = tk.Label(self.stats_frame, text="No Mask: 0", font=("Arial", 11))
        self.mask_label.grid(row=0, column=1, padx=8)

        self.distance_label = tk.Label(self.stats_frame, text="Distance Violations: 0", font=("Arial", 11))
        self.distance_label.grid(row=0, column=2, padx=8)

        self.risk_label = tk.Label(self.frame, text="Risk: LOW", font=("Arial", 13, "bold"), fg="green")
        self.risk_label.pack(pady=2)

        self.status_label = tk.Label(self.frame, text="Status: RUNNING", font=("Arial", 10), fg="blue")
        self.status_label.pack(anchor="w")

    def grid(self, row, col, padx=8, pady=8, sticky="nsew"):
        self.frame.grid(row=row, column=col, padx=padx, pady=pady, sticky=sticky)

    def _set_risk(self, no_mask, distance):
        if no_mask >= 5 or distance >= 5:
            return "HIGH", "red"
        elif no_mask >= 2 or distance >= 2:
            return "MEDIUM", "orange"
        else:
            return "LOW", "green"

    def update_once(self):
        if not self.running:
            return

        ret, frame = self.cap.read()
        if not ret:
            self.status_label.config(text="Status: ENDED / NO FRAME", fg="red")
            self.cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
            return

        self.status_label.config(text="Status: RUNNING", fg="blue")

        locs, preds = detect(frame)
        people = len(locs)

        no_mask = 0
        for pred in preds:
            (mask, withoutMask) = pred
            if withoutMask > mask:
                no_mask += 1

        distance = count_distance_violations(locs)
        risk, color = self._set_risk(no_mask, distance)

        self.people_label.config(text=f"People: {people}")
        self.mask_label.config(text=f"No Mask: {no_mask}")
        self.distance_label.config(text=f"Distance Violations: {distance}")
        self.risk_label.config(text=f"Risk: {risk}", fg=color)

        frame = cv2.resize(frame, (self.cell_w, self.cell_h))
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        img = Image.fromarray(frame)
        imgtk = ImageTk.PhotoImage(image=img)

        self.video_label.imgtk = imgtk
        self.video_label.configure(image=imgtk)

    def stop(self):
        self.running = False
        try:
            self.cap.release()
        except Exception:
            pass

# ------------------ Multi-Fog Dashboard ------------------

class MultiFogDashboard:
    def __init__(self, nodes, window_title="Fog Monitoring Dashboard", update_ms=30):
        self.nodes = nodes
        self.update_ms = update_ms

        self.root = tk.Tk()
        self.root.title(window_title)
        self.root.geometry("1200x750")

        top = tk.Frame(self.root, padx=10, pady=10)
        top.pack(fill="x")

        tk.Label(top, text="Fog Monitoring Dashboard", font=("Arial", 18, "bold")).pack(side="left")
        tk.Button(top, text="Stop All", command=self.stop_all).pack(side="right")

        self.grid_container = tk.Frame(self.root, padx=10, pady=10)
        self.grid_container.pack(fill="both", expand=True)

        self.panels = []
        self._build_grid()

        self.root.protocol("WM_DELETE_WINDOW", self.stop_all)

        self._tick()
        self.root.mainloop()

    def _build_grid(self):
        n = len(self.nodes)
        if n <= 0:
            return

        cols = math.ceil(math.sqrt(n))
        rows = math.ceil(n / cols)

        for c in range(cols):
            self.grid_container.grid_columnconfigure(c, weight=1)
        for r in range(rows):
            self.grid_container.grid_rowconfigure(r, weight=1)

        for idx, (path, name) in enumerate(self.nodes):
            panel = FogPanel(self.grid_container, path, name)
            r = idx // cols
            c = idx % cols
            panel.grid(r, c)
            self.panels.append(panel)

    def _tick(self):
        for p in self.panels:
            p.update_once()
        self.root.after(self.update_ms, self._tick)

    def stop_all(self):
        for p in self.panels:
            p.stop()
        try:
            self.root.destroy()
        except Exception:
            pass

# ------------------ Run ------------------

import json

if __name__ == "__main__":

    # ===============================
    # MODE 1 → Fog Server Worker Mode
    # ===============================
    if len(sys.argv) == 2:

        video = sys.argv[1]

        cap = cv2.VideoCapture(video)
        ret, frame = cap.read()

        if not ret:
            print(json.dumps({
                "people": 0,
                "no_mask": 0,
                "distance_violation": 0
            }))
            sys.exit(0)

        locs, preds = detect(frame)

        people = len(locs)

        no_mask = 0
        for pred in preds:
            (mask, withoutMask) = pred
            if withoutMask > mask:
                no_mask += 1

        distance = count_distance_violations(locs)

        result = {
            "people": people,
            "no_mask": no_mask,
            "distance_violation": distance
        }

        print(json.dumps(result))
        sys.exit(0)

    # ===============================
    # MODE 2 → Dashboard Mode
    # ===============================
    elif len(sys.argv) >= 3:

         nodes = []

         i = 1
         count = 1

         while i < len(sys.argv):
               video = sys.argv[i]

               if i + 1 < len(sys.argv):
                  name = sys.argv[i + 1]
                  i += 1
               else:
                   name = f"Fog Node {count}"

               nodes.append((video, name))
               count += 1
               i += 1

         MultiFogDashboard(nodes)